import React, {
  DetailedHTMLProps,
  HTMLAttributes,
  useRef,
  useEffect,
} from "react";
import { MathfieldElement, MathfieldOptions } from "mathlive";

// some black ts magic to type mathfield web component.
// it basically combines mathlive specific attributes
// with default html attributes and replaces className with class
declare global {
  namespace JSX {
    interface IntrinsicElements {
      ["math-field"]: Partial<MathfieldOptions> &
        Omit<
          DetailedHTMLProps<HTMLAttributes<MathfieldElement>, MathfieldElement>,
          "className"
        > & {
          class?: string;
        };
    }
  }
}

export default function LatexInput({
  defaultValue,
  onInput,
  className,
}: {
  className?: string;
  defaultValue?: string;
  onInput?: (newValue: string) => void;
}) {
  const ref = useRef<MathfieldElement>(null);
  useEffect(() => {
    (async () => {
      import("mathlive");
    })();
  }, []);
  return (
    <math-field
      ref={ref}
      onInput={() => {
        if (ref.current) {
          onInput?.(ref.current.getValue("latex"));
        }
      }}
      class={className}
    >
      {defaultValue}
    </math-field>
  );
}

// latex generated by mathlive is technically correct,
// but it's not recognized by nerdamer, so it has to be fixed
export function fixLatex(markup: string): string {
  return (
    markup
      // fix one-character long parameters for command, like in \frac12 = 1/2
      .replace(
        /(\\[a-z]+)(\d)(\d)?/g,
        (_, command, op1, op2) =>
          `${command}{${op1}}${op2 !== undefined ? `{${op2}}` : ""}`,
      )
      // replace || with abs()
      .replace(/(\\left\|)(.*)(\\right\|)/, "abs($2)")
  );
}
